version: "3.8"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    build: ./etl
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
      etl:
        condition: service_completed_successfully
